version: '3.8'

services:
    mysql:
        platform: linux/x86_64 # m1 mac os
        image: mysql:8.0.27
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mbym
            MYSQL_USER: mbym
            MYSQL_PASSWORD: mbym
            TZ: Asia/Seoul
        volumes:
            - ./volumes/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf
            - ./volumes/mysql/data:/var/lib/mysql
        networks:
            - spring-cloud-app
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            TZ: Asia/Seoul
        networks:
            - spring-cloud-app

networks:
    spring-cloud-app:
        driver: bridge