version: '3.8'

services:
    mysql:
        platform: linux/x86_64 # m1 mac os
        image: mysql:8.0.27
        container_name: mbym-spring_cloud_app-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mbym
            MYSQL_USER: mbym
            MYSQL_PASSWORD: mbym
            TZ: Asia/Seoul
        volumes:
            - ./volumes/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf
            - ./volumes/mysql/data:/var/lib/mysql
        restart: always
        networks:
            - mbym-spring_cloud_app-network
    rabbitmq:
        image: rabbitmq:3-management
        container_name: mbym-spring_cloud_app-rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            TZ: Asia/Seoul
        restart: always
        networks:
            - mbym-spring_cloud_app-network
    zookeeper:
        image: confluentinc/cp-zookeeper:7.0.1
        container_name: mbym-spring_cloud_app-zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        restart: always
        networks:
            - mbym-spring_cloud_app-network
    broker:
        image: confluentinc/cp-server:7.0.1
        container_name: mbym-spring_cloud_app-broker
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
            - "9101:9101"
            - "29092:29092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        restart: always
        networks:
            - mbym-spring_cloud_app-network

networks:
    mbym-spring_cloud_app-network:
        driver: bridge